server:
  port: ${nc.server.port} # 服务端口

spring:
  profiles:
    active: dev # 激活的环境
  application:
    name: Nexa Campus Backend ${nc.project-name} # 项目名称
    version: ${nc.project-version} # 项目版本
  main:
    allow-circular-references: true # 允许循环依赖
  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源类型
    driver-class-name: ${nc.datasource.driver-class-name} # 数据库驱动
    url: ${nc.datasource.url} # 数据库连接地址
    username: ${nc.datasource.username} # 数据库用户名
    password: ${nc.datasource.password} # 数据库密码
  data:
    redis:
      host: ${nc.redis.host} # redis地址
      port: ${nc.redis.port} # redis端口
      database: ${nc.redis.database} # redis数据库
  cache:
    type: redis # 缓存类型
  security:
    user:
      name: admin # 默认用户名
      password: 123456 # 默认用户密码

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml # mapper文件地址, 用于存放MyBatis的XML映射文件
  type-aliases-package: top.nexacampus.backend.pojo.entity # 实体类包名
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    top:
      nexacampus:
        backend:
          controller: info # 控制器日志级别
          service: info # 服务日志级别
          mapper: debug # Mapper日志级别
          config: debug # 配置类日志级别

nc:
  jwt:
    adminSecretKey: ${nc.jwt.adminSecretKey} # 设置jwt签名加密时使用的秘钥
    # (60(秒 = 1分钟) * 60(分钟 = 1小时) * 2 * 1000(单位是毫秒所以*1000)) = 2小时
    adminTtl: ${nc.jwt.adminTtl} # 设置jwt过期时间
    adminTokenName: ${nc.jwt.adminTokenName} # 设置前端传递过来的令牌名称
    user-secret-key: ${nc.jwt.user-secret-key} # 用户秘钥
    user-token-name: ${nc.jwt.user-token-name} # 用户令牌名称
    user-ttl: ${nc.jwt.user-ttl} # 用户过期时间

  alioss:
    endpoint: ${nc.alioss.endpoint} # oss地址
    accessKeyId: ${nc.alioss.accessKeyId} # oss id
    accessKeySecret: ${nc.alioss.accessKeySecret} # oss密钥
    bucketName: ${nc.alioss.bucketName} # oss存储名
    folderName: ${nc.alioss.folderName} # oss存储的文件夹名

  wechat:
    api-v3-key: ${sky.wechat.api-v3-key} # 微信支付v3秘钥
    appid: ${sky.wechat.appid} # 微信appid
    mch-serial-no: ${sky.wechat.mch-serial-no} # 微信商户证书序列号
    mchid: ${sky.wechat.mchid} # 微信商户号
    notify-url: ${sky.wechat.notify-url} # 微信支付回调地址
    private-key-file-path: ${sky.wechat.private-key-file-path} # 微信支付私钥文件路径
    refund-notify-url: ${sky.wechat.refund-notify-url} # 微信退款回调地址
    secret: ${sky.wechat.secret} # 微信支付密钥
    we-chat-pay-cert-file-path: ${sky.wechat.we-chat-pay-cert-file-path} # 微信支付证书文件路径




